### ISSUE TITLE
grunt throwing error

### ISSUE THREAD

**Issue by rajakvk** [archfirst/keel#2]
While trying to install as instructed in readme.md, grunt throwing following error

Running "clean:clean" <clean> task
Warning: Cannot read property 'src' of undefined Use --force to continue.

Aborting due to  warnings.

Any help appreciated...

**Comment by bobholt** [comment]
npm install is not pulling the latest version of grunt-contrib-jshint. To fix this temporarily, go to /node_modules/grunt-contrib-jshint/tasks/jshint.js, search for `file.src` and change it to `filesSrc`.

**Comment by rajakvk** [comment]
After changing as mentioned, I'm getting same warning message.

By the way, tried with filesSrc, fileSrc, filesrc with no luck.

**Comment by bobholt** [comment]
Ah, yes, when I replied, I thought this was on https://github.com/archfirst/bullsfirst-jquery-backbone. 

This architecture hasn't been updated for the latest version of grunt and the plugins, so the build is out of date. This is on my agenda for this week.
