### ISSUE TITLE
Avoid the need for creating blank templates

### ISSUE THREAD

**Issue by nareshbhatia** [archfirst/keel#30]
On several occasions I find myself creating blank templates just to avoid Keel’s default of `<div></div>` - see [Bullsfirst](https://github.com/archfirst/bullsfirst-jquery-backbone) code for several examples. In fact, I don’t think there is a single instance where I have taken advantage of the default.

My suggestion is to test for the case of the template being undefined and in such a case, not ti do template substitutions. It will avoid creation of a whole slew of blank templates. Also I am finding that the views that do D3 visualizations are not template based – they are totally rendered in JavaScript. There is also the case where  markup is completely defined in a parent template and I simply want to hang a view somewhere inside it.

**Comment by bobholt** [comment]
It was always possible to pass in an empty string for the template:

```
template: {
  name: 'myTemplate',
  source: ''
}
```

but that's definitely less than ideal, so I added the ability to just null it out:

`template:null`

I left the default `template: {name:'DefaultTemplate', source:'<div></div>}'` for backwards compatibility in case anything or anyone with a fork has relied on it.

New functionality, so I'll tag this release as 1.1.0

**Comment by nareshbhatia** [comment]
Thank you! Will definitely help reduce boilerplate code. Will be switching over to 1.1.0 in Bullsfirst as soon as we get a chance.

**Comment by bobholt** [comment]
Already switched it for you. Check out AccountChartWidget.

**Comment by nareshbhatia** [comment]
You are the best!

I found that the AccountChartTemplate define was still left in the file. Took that out too - one line less! I wonder why require was not complaining out this non-existent dependency!
