### ISSUE TITLE
Document the pattern on placing element in DOM

### ISSUE THREAD

**Issue by nareshbhatia** [archfirst/keel#31]
`BaseView.addChild()` has a parameter called `parentElement`. It's usage needs to be properly documented. One cannot blindly put `parentElement: this.$el` when calling `addChild()`. It is required only if we are creating a new DOM node and “placing” it under the parent. In situations where we are simply hanging a view off of existing markup, then `parentElement` should be left undefined, instead `options.el` should be defined.

So we have two patterns:

**Creating new DOM nodes**

```
postRender: function() {
    this.addChildren([
        {
            id: 'OutputPanel',
            viewClass: OutputPanel,
            parentElement: this.$el
        }
    ]);
}
```

**Attaching views to existing DOM nodes**

```
postRender: function() {
    this.addChildren([
        {
            id: 'Dashboard',
            viewClass: Dashboard,
            options: {
                el: this.dashboardElement
            }
        }
    ]);
}
```

**Comment by bobholt** [comment]
Closing. Added documentation on Child View creation patterns: https://github.com/archfirst/keel/wiki/Creating-Child-Views
