### ISSUE TITLE
Add Ruby and Compass to requirements

### ISSUE THREAD

**Issue by nareshbhatia** [archfirst/keel#33]
Add Ruby and Compass to requirements - without this the build instructions will not work.

We could almost use [Trader Desktop build instructions](https://github.com/archfirst/trader-desktop) for this project - they are quite comprehensive. In fact, if we instruct people to run the app with Node, then many of the complications of setting appRoot can be avoided for the beginner.

**Comment by bobholt** [comment]
I updated the Installation page of the Wiki to better define the installation process (borrowing from Trader Desktop).

https://github.com/archfirst/keel/wiki/Installation

I hesitate to set up a node server in the repository. I'm even considering removing the demo application from the Keel repo and setting up a separate sample application.
